### ISSUE TITLE
repo isn't on hex

### ISSUE THREAD

**Issue by codestorm1** [absinthe-graphql/absinthe_ecto#12]
Hi, we broke our build today because the versions changed.
Any reason this repo couldn't be hosted on hex.pm?

Thanks

**Comment by benwilson512** [comment]
Hey!

I am placing it on hex now, it's mostly just an oversight.

Can you elaborate on how the build was broken? Your mix.lock file will lock both git dependencies as well as hex dependencies, so pushing additional code on our end won't force updates on your end.

**Comment by codestorm1** [comment]
I'll mention this issue to my co-worker who had to break, maybe he can elaborate.

Thanks for adding it to Hex!

**Comment by lvalencia** [comment]
he's talking about our docker-build (or any build that runs `mix deps.get`)  because it will get latests and the latest push had dependencies that we didn't meet, so we had to update our dependencies. It wasn't anything major but it was unexpected.

**Comment by benwilson512** [comment]
Are you including the mix.lock file in your docker build? I was under the impression that even for git dependencies a `mix deps.get` would only get the locked git ref unless explicitly unlocked.

**Comment by lvalencia** [comment]
Yeah I understand what you're saying, the answer is I'm not sure man, we're using it as part of the edib package https://github.com/edib-tool/elixir-docker-image-builder if that helps.

**Comment by benwilson512** [comment]
I would definitely try to figure out what dockerfile is being used by that tool. If your mix.lock file is not being included, you're gonna end up with a lot of bugs when libraries in production don't match libraries in development. In any case, we're on hex now.
