### ISSUE TITLE
Support for custom foreign_key?

### ISSUE THREAD

**Issue by bjunc** [absinthe-graphql/absinthe_ecto#30]
It appears that the association is stitching together the field name and custom `@primary_key`, but ignoring `foreign_key`.

**Comment by benwilson512** [comment]
I'm not sure I understand. Absinthe.Ecto doesn't explicitly use the primary key, or any other key at all. It relies entirely on your Ecto associations.

**Comment by bjunc** [comment]
Thanks for getting back to me @benwilson512.  I believe this was user error.  I was attempting to handle associations from a database that started its life as Drupal; which has a mixture of unconventional primary keys and foreign keys.  

To simplify things, I created a test scenario that required custom foreign keys, and all went well (eerily well, actually).  It looks something like this (loosely mimicking [Facebook's Post Graph API](https://developers.facebook.com/docs/graph-api/reference/v2.10/post)):

```elixir
# ecto schema
schema "posts" do
  field :message, :string
  belongs_to :from, User, foreign_key: :from_user_id
  belongs_to :to, User, foreign_key: :to_user_id

  timestamps()
end
```

```elixir
# graphql types
object :user do
  field :id, :id
  field :email, :string
  field :first_name, :string
  field :last_name, :string
  field :wall, list_of(:post), resolve: assoc(:wall)
end

object :post do
  field :id, :id
  field :message, :string
  field :from, :user, resolve: assoc(:from)
end
```

```graphql
# graphql query
{
  user (id: 1) {
    wall {
      message
      from {
        firstName
        lastName
      }
    }
  }
}
```
This results in two queries (one for posts, and one for users).  Awesome!

**Comment by benwilson512** [comment]
Cool!

**Comment by rmap96** [comment]
@bjunc hello, I'm trying something similar, how did you define your "users" schema?
