### ISSUE TITLE
warning: this check/guard will always yield the same result

### ISSUE THREAD

**Issue by ndarilek** [absinthe-graphql/absinthe_ecto#8]
Getting this error with the following:

```
    field :orders, list_of(:order), resolve: assoc(:orders)
```

Am I doing something wrong here? Fairly new to Elixir but think that's a fairly accurate copy from the docs. :)

Thanks.

**Comment by MartinElvar** [comment]
@ndarilek I believe it would be a great help for the maintainers, if you provided the error as well. :)

**Comment by ndarilek** [comment]
That *is* the warning, there is no error. Code lifted straight out of 
the docs:

     field :orders, list_of(:order), resolve: assoc(:orders)

Am I misunderstanding what you're saying?

**Comment by benwilson512** [comment]
Fixed in master.
